sudo: false

language: python

matrix:
  include:
    - os: linux
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gcc-4.9
      env:
        - PYTHONPATH=$PWD
        - CC=gcc-4.9
        - CXX=g++-4.9

    - os: linux
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
        - PYTHONPATH=$PWD
        - CC=gcc-5
        - CXX=g++-5

    - os: linux
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env:
        - PYTHONPATH=$PWD
        - CC=gcc-6
        - CXX=g++-6
    - os: linux
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - PYTHONPATH=$PWD
        - CC=gcc-7
        - CXX=g++-7
    - os: linux
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      env:
        - PYTHONPATH=$PWD
        - CC=gcc-8
        - CXX=g++-8


    - os: osx
      osx_image: xcode8.3
      python: "3.6-dev"
      env: PYTHONPATH=$PWD


    - os: osx
      osx_image: xcode8.3
      python: "3.6-dev"
      before_install:
        - brew install gcc@8
      env:
        - PYTHONPATH=$PWD
        - CC=gcc-8
        - CXX=g++-8


script:
  - pip install -e .
  - py.test -svx test.py
